<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rahul-Dev-Ghosh" failures="1" tests="11" name="Salesforce Test Cases" time="56.907" errors="0" timestamp="2022-05-16T01:06:21 IST">
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="loginPageLogoTest" time="0.058"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="loginPageTitleTest" time="0.006"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLogin" time="6.594">
    <failure type="java.lang.AssertionError" message="expected [Home | Salesforce] but found [Lightning Experience]">
      <![CDATA[java.lang.AssertionError: expected [Home | Salesforce] but found [Lightning Experience]
at com.salesforce.testcases.LoginPageTest.validateLogin(LoginPageTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validateLogin -->
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLoginNegativeScenarios" time="0.462"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLoginNegativeScenarios" time="0.406"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLoginNegativeScenarios" time="7.739"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLoginNegativeScenarios" time="0.447"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLoginNegativeScenarios" time="0.401"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLoginNegativeScenarios" time="0.408"/>
  <testcase classname="com.salesforce.testcases.LoginPageTest" name="validateLoginNegativeScenarios" time="0.404"/>
  <testcase classname="com.salesforce.testcases.DashboardPageTest" name="verifyAllTabsOnDashboardPage" time="7.003"/>
</testsuite> <!-- Salesforce Test Cases -->
